"""updated booking: {booking_time, last_modified}

Revision ID: 209f39d3e6f1
Revises: 4c016f07530b
Create Date: 2020-01-13 12:34:00.328356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209f39d3e6f1'
down_revision = '4c016f07530b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('book_time', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'last_modified')
    op.drop_column('bookings', 'book_time')
    # ### end Alembic commands ###
