"""event desc nullY

Revision ID: 264641c51e52
Revises: 8edfa8519c68
Create Date: 2020-01-20 18:52:45.902946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264641c51e52'
down_revision = '8edfa8519c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
